/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceDeviceRouteImport } from './routes/_workspace/device'
import { Route as WorkspaceJobRouteImport } from './routes/_workspace/job'
import { Route as WorkspacePrepareRouteImport } from './routes/_workspace/prepare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDeviceRoute = WorkspaceDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceJobRoute = WorkspaceJobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePrepareRoute = WorkspacePrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/device': typeof WorkspaceDeviceRoute
  '/job': typeof WorkspaceJobRoute
  '/prepare': typeof WorkspacePrepareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/device': typeof WorkspaceDeviceRoute
  '/job': typeof WorkspaceJobRoute
  '/prepare': typeof WorkspacePrepareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_workspace/device': typeof WorkspaceDeviceRoute
  '/_workspace/job': typeof WorkspaceJobRoute
  '/_workspace/prepare': typeof WorkspacePrepareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/device' | '/job' | '/prepare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/device' | '/job' | '/prepare'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/settings'
    | '/_workspace/device'
    | '/_workspace/job'
    | '/_workspace/prepare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/device': {
      id: '/_workspace/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof WorkspaceDeviceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/job': {
      id: '/_workspace/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof WorkspaceJobRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/prepare': {
      id: '/_workspace/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof WorkspacePrepareRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceDeviceRoute: typeof WorkspaceDeviceRoute
  WorkspaceJobRoute: typeof WorkspaceJobRoute
  WorkspacePrepareRoute: typeof WorkspacePrepareRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceDeviceRoute: WorkspaceDeviceRoute,
  WorkspaceJobRoute: WorkspaceJobRoute,
  WorkspacePrepareRoute: WorkspacePrepareRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
